### ISSUE TITLE
Use Promise.resolve rather that creating a new promise object

### ISSUE THREAD

**Issue by howarddierking** [gdereese/vorpal-openapi#31]
I'm not sure whether it's a requirement that actions return a promise from the `run` function, but based on https://github.com/gdereese/vorpal-openapi/blob/9b38a80d2af21764f385ed8b310a5955c4bedc81/src/about-command-action.ts#L10 that seems to be the case. At any rate, if the code simply needs to return a promise but doesn't actually do anything async, you should use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve rather than creating a new `Promise` instance and then manually calling resolve on it. For one thing, this approach will save you from cases where you miss calling `reject`.

**Comment by gdereese** [comment]
Yep, duh.  Good catch.
