### ISSUE TITLE
Consider replacing string concatenation with template literals

### ISSUE THREAD

**Issue by howarddierking** [gdereese/vorpal-openapi#32]
There's a lot of strong concatenation in the code base. Consider replacing it with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

There's probably some performance benefit to using this approach in terms of fewer immutable allocated strings, but I think it's just generally cleaner.

**Comment by gdereese** [comment]
Makes sense.  I've always preferred that kind of approach in C# with `string.Format()` or interpolated strings, but didn't realize an equivalent existed in JS.  Thanks for the tip!
